### ISSUE TITLE
打开dialog窗口抖动

### ISSUE THREAD

**Issue by 593496637** [un-pany/v3-electron-vite#12]
打开这个按钮，显示窗口时会出现抖动情况，掉帧比较明显

<img width="1173" alt="image" src="https://github.com/un-pany/v3-electron-vite/assets/15769004/ea37e877-ebe1-4f1d-be2e-abacf5cc8303">

**Comment by 593496637** [comment]
打开侧边栏有比较明显的拖影，不知道能否优化
![GIFMaker_me](https://github.com/un-pany/v3-electron-vite/assets/15769004/42c4ec2e-59fa-440d-bd1c-6ccc03a5b213)

**Comment by 593496637** [comment]
硬件环境：
macbook pro m1芯片
node 18
vscode

**Comment by pany-ang** [comment]
> 打开侧边栏有比较明显的拖影，不知道能否优化 ![GIFMaker_me](https://user-images.githubusercontent.com/15769004/264076183-42c4ec2e-59fa-440d-bd1c-6ccc03a5b213.gif)

拖影指的是啥？黑色背景有一点延迟？还是抽屉打开时的渐入渐出动画？

**Comment by pany-ang** [comment]
你先手动将 element-plus 升级为 2.3.12 试试看，是否解决了你提到的两个问题？

**Comment by 593496637** [comment]
两个都是动画问题，可能是element本身动画做的不是太好

**Comment by pany-ang** [comment]
在浏览器上运行挺流畅的。这个问题不好排查，可能是 Element Plus 本身的问题，可能是 Electron 的问题，但也可能我们的配置问题

**Comment by pany-ang** [comment]
我测试了一下，在窗口比较大时掉帧比较明显，窗口比较小时，几乎无掉帧 @nevlf

**Comment by 593496637** [comment]
> 我测试了一下，在窗口比较大时掉帧比较明显，窗口比较小时，几乎无掉帧 @nevlf

确实是这样的，窗口一大，就会卡顿的很明显
