### ISSUE TITLE
 Preprocessor dependency "sass" failed to load: Cannot read properties of undefined (reading 'pop')

### ISSUE THREAD

**Issue by naonao-a** [un-pany/v3-electron-vite#14]
![image](https://github.com/un-pany/v3-electron-vite/assets/54222304/38874e42-d7d4-4d81-9619-2cba172fc340)
anzhuang安装依赖后运行报错怎么解决呀

**Comment by nevlf** [comment]
试试 npm cache clean --force 清除缓存，删除 node_modules 文件夹后再重新安装依赖呢
