### ISSUE TITLE
更改路由页面加载不刷新

### ISSUE THREAD

**Issue by yun3948** [un-pany/v3-electron-vite#15]
请教一下，我这边项目使用了这个后台，新增了几个菜单在顶部， 路由里面meta设置的 hidden ，然后现在发现点击菜单页面是空白的，然后需要缩小或者窗口，触发渲染才能显示出来， 初步排查 是 布局 Transition 组件有影响，  不知道是哪里的问题？

**Comment by pany-ang** [comment]
检查一下相关页面是否保证了唯一根节点元素

**Comment by yun3948** [comment]
确实是，有一个页面不是唯一根节点。感谢感谢
