### ISSUE TITLE
Electron主进程代码文件夹名称问题

### ISSUE THREAD

**Issue by xqyi** [un-pany/v3-electron-vite#16]
存放Electron主进程代码的文件夹我看很多都是以electron命名的，如下
![image](https://github.com/un-pany/v3-electron-vite/assets/3350573/30bc04be-873a-46c7-b6a9-4ebb943c9964)

为什么这里不以这种规则命名呢？

**Comment by nevlf** [comment]
是因为没有用到preload，而且将主进程代码按模块分离了，就没有以这种命名。
