### ISSUE TITLE
能否支持浏览器打包

### ISSUE THREAD

**Issue by 593496637** [un-pany/v3-electron-vite#19]
我们现在有个项目开发接近尾声了，但是有个新需求是想要打包为浏览器端，能否实现？
比如：
pnpm run browser:dev
pnpm run browser:build

**Comment by nevlf** [comment]
意思是只打包渲染进程？

**Comment by 593496637** [comment]
意思是可否用浏览器打开，支持打包为web浏览器界面

**Comment by nevlf** [comment]
这个恐怕不支持，如果你的渲染进程源码不涉及node.js、electron相关api、是个纯web项目，完全可以迁到v3-admin进行打包

**Comment by 593496637** [comment]
没办法了也只能这样做了，不过我确实是纯web的，没有涉及到node，electron。
不过有个项目是做了这个功能的，可以作为参考，有空了可以参考下，https://github.com/pure-admin/electron-pure-admin
