### ISSUE TITLE
MacOS升级了15版本无法打包了

### ISSUE THREAD

**Issue by 593496637** [un-pany/v3-electron-vite#21]
MacOS升级了15版本无法打包了，现在后悔中，又无法回退系统了，作者要有这个环境做测试的话帮忙看看，不过毕竟还是beta版，没有环境就算了，我想想办法看能回退系统么

**Comment by 593496637** [comment]
会卡在这里不动
![Uploading image.png…]()

**Comment by 593496637** [comment]
会卡在这里不动
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/c6e6858c-bf96-4026-b111-f0fb1e15b12b">

**Comment by 593496637** [comment]
我使用的是最新模板作为打包项目

**Comment by nevlf** [comment]
检查一下是不是系统权限问题呢，我刚才试了一下，打包时有弹出一个访问权限修改
<img width="1032" alt="截屏2024-07-29 09 39 59" src="https://github.com/user-attachments/assets/1d9a9400-0e45-4584-930d-c7792a8b59fc">
<img width="650" alt="截屏2024-07-29 09 40 42" src="https://github.com/user-attachments/assets/2ccf89d4-c4da-4748-94c5-75763da03865">

**Comment by 593496637** [comment]
感谢回答，目前已恢复正常
