### ISSUE TITLE
拉去下来，启动报错，该怎么处理

### ISSUE THREAD

**Issue by sunlight-lg** [un-pany/v3-electron-vite#22]
![image](https://github.com/user-attachments/assets/5255530c-a503-4799-8642-c0998928ba97)
v3-electron-admin项目拉去下来，安装完依赖，启动时候报错，这个还怎么处理，
![image](https://github.com/user-attachments/assets/6d1225e3-338c-417a-821d-82a535c998fa)

**Comment by nevlf** [comment]
抱歉，暂时没能复现这个问题
