### ISSUE TITLE
项目拉去下来打包，报错不能打包成功，应该怎么处理

### ISSUE THREAD

**Issue by sunlight-lg** [un-pany/v3-electron-vite#23]
项目安装完依赖，打包build就会报错，打包不成功，这个应该怎么处理
![image](https://github.com/user-attachments/assets/9f17516c-db1c-4243-978e-b6a4d9d3c7a8)
![image](https://github.com/user-attachments/assets/f8e35e78-3bf4-4b9b-a58b-e32a817ff795)
![image](https://github.com/user-attachments/assets/73a1b56e-66be-4303-a5e2-933bfd305a8a)

**Comment by nevlf** [comment]
先使用管理员身份执行打包命令，之后就可以在vscode中正常打包
