### ISSUE TITLE
请教下渲染进程如何和主进程通信 

### ISSUE THREAD

**Issue by a184734919** [un-pany/v3-electron-vite#26]
/** 监听通信事件 */
  static ipcListening() {
    // 设置窗口默认尺寸
    ipcMain.on(IpcDict.CODE_01001, (_, dto: WinStateDTO) => {
      if (!this.winInst) return
      const size = AppConfig.adaptByScreen(dto, this.winInst)
      this.winInst.setResizable(true)
      this.winInst.setMinimumSize(size.width, size.height)
      this.winInst.setSize(size.width, size.height)
      dto.center && this.winInst.center()
      typeof dto.maxable === "boolean" && this.winInst.setMaximizable(dto.maxable)
      typeof dto.resizable === "boolean" && this.winInst.setResizable(dto.resizable)
    })
    // 中转消息-代替中央事件总线
    ipcMain.on(IpcDict.CODE_02002, (_, args: any) => {
      if (!this.winInst || !args || !args.channel) return
      this.printf("[main.win.事件总线]", args)
      this.sendToRenderer(args.channel, args.data)
    })
  }

**Comment by nevlf** [comment]
在 App.vue 中有使用 ipcRenderer.send() 向主进程发送消息。当然，使用 ipcRenderer.on() 可以监听主进程发送的消息。

**Comment by a184734919** [comment]
感谢感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [un-pany/v3-electron-vite] 请教下渲染进程如何和主进程通信  (Issue #26)




 
在 App.vue 中有使用 ipcRenderer.send() 向主进程发送消息。当然，使用 ipcRenderer.on() 可以监听主进程发送的消息。
