### ISSUE TITLE
如何将vue部分创建在项目中

### ISSUE THREAD

**Issue by Alex0314H** [un-pany/v3-electron-vite#5]
本项目中vue的部分如何直接运行在浏览器中测试呢？

**Comment by pany-ang** [comment]
没理解你说的什么意思，Vue 部分的代码，完全来自于：[v3-admin-vite](https://github.com/un-pany/v3-admin-vite)，你可以直接运行这个项目

**Comment by Alex0314H** [comment]
> 没理解你说的什么意思，Vue 部分的代码，完全来自于：[v3-admin-vite](https://github.com/un-pany/v3-admin-vite)，你可以直接运行这个项目

是这样的，在项目中增加了部分代码之后，我想在浏览器中进行运行和调试而不是在electron里，看过之前的vite项目，按照之前的运行方式无法在这个项目中生效。

**Comment by pany-ang** [comment]
意思是要在 electron 中写代码，然后运行到浏览器中调试？如果是这样的话，我没做过这样的尝试，不太清楚可不可行
