### ISSUE TITLE
有沒有辦法使用瀏覽器開啟？

### ISSUE THREAD

**Issue by ontisme** [un-pany/v3-electron-vite#9]
electron的專案想要使用瀏覽器時，我測試都會出現 require 不支援的問題，或是奇怪的Path問題，也理解報這錯的原因。

但這個問題是有辦法解決的嗎？讓我能選擇或是同時使用瀏覽器運行呢，謝謝大佬。

**Comment by nevlf** [comment]
开发环境下，可以将 vite.config.ts 中的 server.open 设置为 true，这样就能在浏览器中访问。但是如果需要使用 electron 相关的 api，就会出现你说的那些问题，所以还是不建议使用浏览器运行。electron 本身就集成 chromium，也可以使用控制台进行调试的。

**Comment by ontisme** [comment]
了解，因為我的軟件比較特殊，需要可以局域網訪問比較方便，但又想有桌面版本，Electron的功能本身用的不多，我用的後端是Python，所以可以把Electron的功能改到後端實現

**Comment by nevlf** [comment]
你这种情况，可以把渲染进程的src源码完全替换成web版的源码，这样就只需要维护一套环境的代码。但是有些的地方需要注意，比如electron打包后不支持cookie、后台接口地址也要固定写死的
